name: thread_rift
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  firebase_core: ^2.30.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_riverpod: ^2.5.1
  formz: ^0.7.0
  go_router: ^13.2.4
  google_fonts: ^6.2.1
  jwt_decode: ^0.3.1
  jwt_decoder: ^2.0.1
  riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  supabase_flutter: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
    - assets/images/
    - assets/logos/
    - google_fonts/mulish/