// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkPrZt1BP0RvHC6BWDL0CHrViE5v8d4Js',
    appId: '1:229858705877:web:3151ea7465afc903d5fd5c',
    messagingSenderId: '229858705877',
    projectId: 'threadrift-a08ec',
    authDomain: 'threadrift-a08ec.firebaseapp.com',
    storageBucket: 'threadrift-a08ec.appspot.com',
    measurementId: 'G-JGXJ03MMNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWbw6ahMYL09WfkbuUlXhxrA-SmOeiGFQ',
    appId: '1:229858705877:android:a399841b02ebf1a4d5fd5c',
    messagingSenderId: '229858705877',
    projectId: 'threadrift-a08ec',
    storageBucket: 'threadrift-a08ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2XtpyjNpanSDGC7eJ-mQ7HStnR4xRF6Q',
    appId: '1:229858705877:ios:1bd5af71fac67bedd5fd5c',
    messagingSenderId: '229858705877',
    projectId: 'threadrift-a08ec',
    storageBucket: 'threadrift-a08ec.appspot.com',
    iosBundleId: 'com.example.threadRift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2XtpyjNpanSDGC7eJ-mQ7HStnR4xRF6Q',
    appId: '1:229858705877:ios:1bd5af71fac67bedd5fd5c',
    messagingSenderId: '229858705877',
    projectId: 'threadrift-a08ec',
    storageBucket: 'threadrift-a08ec.appspot.com',
    iosBundleId: 'com.example.threadRift',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkPrZt1BP0RvHC6BWDL0CHrViE5v8d4Js',
    appId: '1:229858705877:web:2dc47b8aecff323bd5fd5c',
    messagingSenderId: '229858705877',
    projectId: 'threadrift-a08ec',
    authDomain: 'threadrift-a08ec.firebaseapp.com',
    storageBucket: 'threadrift-a08ec.appspot.com',
    measurementId: 'G-KYVNCK1R8B',
  );
}
